# Generated by Django 2.1.8 on 2019-10-02 05:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Отделение')),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель')),
                ('note', models.CharField(default='', max_length=50, verbose_name='Примечание')),
                ('dt', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('bild', models.ForeignKey(default='', on_delete=None, to='examples.bild', verbose_name='Корпус')),
                ('dep', models.ForeignKey(default='', on_delete=None, to='examples.dep', verbose_name='Отделение')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель')),
                ('note', models.CharField(default='', max_length=50, verbose_name='Примечание')),
                ('dt', models.DateTimeField(default=datetime.datetime.now)),
                ('bild', models.ForeignKey(default='', on_delete=None, to='examples.bild')),
                ('dep', models.ForeignKey(default='', on_delete=None, to='examples.dep')),
                ('id_eq', models.ForeignKey(default='', on_delete=None, to='examples.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='ter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Территория')),
            ],
        ),
        migrations.CreateModel(
            name='type_eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип оборудования')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.ForeignKey(default='', on_delete=None, to='examples.status'),
        ),
        migrations.AddField(
            model_name='history',
            name='ter',
            field=models.ForeignKey(default='', on_delete=None, to='examples.ter'),
        ),
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.ForeignKey(default='', on_delete=None, to='examples.type_eq'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(default='', on_delete=None, to='examples.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ter',
            field=models.ForeignKey(default='', on_delete=None, to='examples.ter', verbose_name='Территория'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(default='', on_delete=None, to='examples.type_eq'),
        ),
    ]
